name: JailSystem
main: fr.ideeess.main.JailSystem
version: 0.0.1
author: IDEEESS
commands:
  setjail:
    description: Set les différents paramètres
  jail:
    description: Met en prison une personne